// src/components/landing-page.tsx
const galleryImages = Array.from({ length: 22 }, (_, index) => {
  const id = index + 1;
  return {
    id,
    url: `/assets/img/image${String(id).padStart(5, '0')}.jpeg`,
    alt: `NITIDO Barber Studio galería ${id}`,
  };
});

const services = [
  ['CORTE MODERNO 12€', '(TIEMPO APROX. 35 MIN)'],
  ['CORTE Y CEJAS 14€', '(TIEMPO APROX. 35 MIN)'],
  ['CORTE Y BARBA 17€', '(TIEMPO APROX. 45 MIN)'],
  ['CORTE Y LAVADO 15€', '(TIEMPO APROX. 35 MIN)'],
  ['CORTE, BARBA Y CEJAS 19€', '(TIEMPO APROX. 45 MIN)'],
  ['CORTE, BARBA, CEJAS Y LAVADO 22€', '(TIEMPO APROX. 60 MIN)'],
  ['CORTE PREMIUM 15€', '(TIEMPO APROX. 45 MIN)'],
  ['CORTE NIÑO O JUBILADO 7€', '(TIEMPO APROX. 20 MIN)'],
  ['ARREGLO DE BARBA 8€', '(TIEMPO APROX. 15 MIN)'],
  ['MECHAS 35€', '(INCLUYE CORTE. TIEMPO APROX. 150 MIN)'],
  ['DECOLORACIÓN 55€', '(INCLUYE CORTE. TIEMPO APROX. 180MIN)'],
];

const bookingUrl =
  'https://booksy.com/es-es/124137_nitido-barber-studio_barber-shop_101746_zaragoza';

export function LandingPage() {
  return (
    <>
      <div className="hero w-full h-screen flex">
        <div className="container-fluid m-0 px-0 flex flex-row h-full">
          <div className="col-sm-6 col-md-6 flex flex-col justify-center items-center p-0 m-auto ">
            <a
              href="https://www.instagram.com/nitido.barberstudio"
              target="_blank"
              rel="noopener noreferrer"
            >
              <div className="m-auto p-0">
                <img
                  className="max-w-full max-h-full  rounded-lg transform transition duration-300 hover:scale-105 hover:shadow-2xl"
                  src="/assets/img/logo2.png"
                  alt="Nitido"
                />
              </div>
            </a>

            <div className="hero-text text-center p-4 ">
              <p className="text-gray-800 text-lg md:text-xl font-light leading-relaxed">
                Tu imagen, Nuestra pasión. En NITIDO cada detalle está pensado
                para ti. ¡Ven y disfruta de un servicio de calidad donde la
                precisión y el buen gusto se encuentra!
              </p>
            </div>

            <div className="m-auto p-2 w-full max-w-52 bg-gray-200 bg-opacity-75 text-gray-800 rounded-lg shadow-lg transition duration-300 hover:bg-black hover:text-white">
              <a
                href={bookingUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="block no-underline text-lg md:text-xl hover:font-light leading-relaxed text-center"
              >
                <span>Reservar</span>
              </a>
            </div>

            <div className="mt-1.5 p-2 w-full max-w-52 bg-gray-200 bg-opacity-75 text-gray-800 rounded-lg shadow-lg transition duration-300 hover:bg-black hover:text-white">
              <a
                href="#servicios"
                rel="noopener noreferrer"
                className="no-underline block text-lg md:text-xl hover:font-light leading-relaxed text-center"
              >
                <span>Ver los servicios</span>
              </a>
            </div>
          </div>

          <div
            className="col-sm-6 col-md-6 p-0 bg-cover bg-center"
            style={{ backgroundImage: "url('/assets/img/image00001.jpeg')" }}
          />
        </div>
      </div>

      <div className="team bg-gray-100">
        <div className="container mx-auto py-16">
          <div className="section-header text-center mb-12">
            <h2 className="text-5xl font-bold font-bold text-black">
              CONOZCA A NUESTRO BARBERO
            </h2>
          </div>

          <div className="text-center p-4">
            <p className="text-gray-800 text-lg md:text-xl font-light leading-relaxed">
              En NITIDO, nos especializamos en resaltar lo mejor de tu estilo
              con precisión y detalle. Ya sea que busques un corte clásico,
              moderno o algo único, nuestro equipo está listo para ofrecerte un
              servicio impecable en un ambiente relajado y cómodo. Cada visita a
              nuestra barbería es una experiencia pensada para ti, porque
              sabemos que un buen corte no es solo una cuestión de apariencia,
              es una declaración de personalidad.{' '}
            </p>
          </div>

          <div className="flex flex-nowrap justify-center gap-10">
            <div className="team-item bg-white shadow-lg rounded-lg overflow-hidden transform transition duration-300 hover:scale-105 hover:shadow-2xl">
              <a
                href="https://www.instagram.com/blaskkoo"
                className="no-underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="team-img">
                  <img
                    className="w-80 h-80 object-cover transition duration-300 transform hover:scale-110 hover:opacity-90"
                    src="/assets/img/blasko.jpeg"
                    alt="Team Image"
                  />
                </div>
                <div className="team-text text-center p-6">
                  <p
                    className="text-3xl font-bold text-gray-800"
                    style={{ fontFamily: 'NewYork' }}
                  >
                    BLASKO
                  </p>
                </div>
              </a>
            </div>
          </div>
        </div>

        <div
          id="servicios"
          className="py-16 bg-gray-900 bg-cover bg-center"
          style={{ backgroundImage: "url('/assets/img/image00016.jpeg')" }}
        >
          <div className="container mx-auto">
            <div className="text-center mb-12">
              <h1
                className="text-5xl font-bold text-white"
                style={{ fontFamily: 'NewYork' }}
              >
                SERVICIOS
              </h1>
            </div>

            <div className="flex flex-wrap lg:flex-nowrap justify-center">
              <div className="w-full lg:w-2/3 mb-8 lg:mb-0 bg-gray-700 bg-opacity-60 rounded-2xl m-6">
                <ul className="grid grid-cols-1 sm:grid-cols-2 gap-6 mt-6">
                  {services.map(([name, time]) => (
                    <li key={name}>
                      <p className="text-xl font-semibold text-white">
                        {name}
                      </p>
                      <p className="text-sm text-white">{time}</p>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            <div className="m-auto mt-4 p-2 w-full max-w-52 bg-gray-200 bg-opacity-40 text-black font-semibold rounded-lg shadow-lg transition duration-300 hover:bg-black ">
              <a
                href={bookingUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="block no-underline text-lg md:text-xl hover:font-dark leading-relaxed text-center"
              >
                <span>RESERVAR</span>
              </a>
            </div>
          </div>
        </div>

        <div className="py-16 bg-gray-900 overflow-hidden">
          <div className="container mx-auto">
            <div className="text-center mb-12">
              <h2
                className="text-5xl font-bold text-white"
                style={{ fontFamily: 'NewYork' }}
              >
                GALERIA
              </h2>
              <h3
                className="text-3xl font-bold text-white mt-4"
                style={{ fontFamily: 'NewYork' }}
              >
                EXPLORA NUESTRO ESPACIO
              </h3>
            </div>

            <div className="relative">
              <div id="carousell" className="flex gap-6 grid-rows-2 animate-scroll">
                {galleryImages.map((image) => (
                  <div
                    className="image-item flex-none w-80 h-64 overflow-hidden rounded-lg shadow-lg"
                    key={image.id}
                  >
                    <img
                      className="w-full h-full object-cover"
                      src={image.url}
                      alt={image.alt}
                    />
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

// src/app/components/landing-page/landing-page.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-landing-page',
  standalone: true,
  imports: [],
  templateUrl: './landing-page.component.html',
  styleUrl: './landing-page.component.css'
})
export class LandingPageComponent {
  images = [
    {id:1, url: 'assets/img/image00001.jpeg', alt: 'Image 1'},
    {id:2, url: 'assets/img/image00002.jpeg', alt: 'Image 2'},
    {id:3, url: 'assets/img/image00003.jpeg', alt: 'Image 3'},
    {id:4, url: 'assets/img/image00004.jpeg', alt: 'Image 4'},
    {id:5, url: 'assets/img/image00005.jpeg', alt: 'Image 5'},
    {id:6, url: 'assets/img/image00006.jpeg', alt: 'Image 6'},
    {id:7, url: 'assets/img/image00007.jpeg', alt: 'Image 7'},
    {id:8, url: 'assets/img/image00008.jpeg', alt: 'Image 8'},
    {id:9, url: 'assets/img/image00009.jpeg', alt: 'Image 9'},
    {id:10, url: 'assets/img/image00010.jpeg', alt: 'Image 10'},
    {id:11, url: 'assets/img/image00011.jpeg', alt: 'Image 11'},
    {id:12, url: 'assets/img/image00012.jpeg', alt: 'Image 12'},
    {id:13, url: 'assets/img/image00013.jpeg', alt: 'Image 13'},
    {id:14, url: 'assets/img/image00014.jpeg', alt: 'Image 14'},
    {id:15, url: 'assets/img/image00015.jpeg', alt: 'Image 15'},
    {id:16, url: 'assets/img/image00016.jpeg', alt: 'Image 16'},
    {id:17, url: 'assets/img/image00017.jpeg', alt: 'Image 17'},
    {id:18, url: 'assets/img/image00018.jpeg', alt: 'Image 18'},
    {id:19, url: 'assets/img/image00019.jpeg', alt: 'Image 19'},
    {id:20, url: 'assets/img/image00020.jpeg', alt: 'Image 20'},
    {id:21, url: 'assets/img/image00021.jpeg', alt: 'Image 21'},
    {id:22, url: 'assets/img/image00022.jpeg', alt: 'Image 22'},
  ];
  currentIndex: number = 0;

  ngOnInit(): void {}

  next() {
    this.currentIndex = (this.currentIndex + 1) % this.images.length;
  }

  prev() {
    this.currentIndex = (this.currentIndex - 1 + this.images.length) % this.images.length;
  }


}


<!--todo terminar de agregar imagenes-->
<!--todo agregar ubicacion de google map-->
<!--todo mas adelante sistema de reservas-->

<!--logo-->
<!--<div class="container w-full m-auto">-->
<!--  <div class="row m-auto">-->
<!--    <img class="w-full" src="assets/img/logo2.png" alt="Nitido">-->
<!--  </div>-->
<!--</div>-->
<!--logo end-->


<!-- Hero Start -->
<div class="hero w-full h-screen flex">
  <div class="container-fluid m-0 px-0 flex flex-row h-full">
    <div class="col-sm-6 col-md-6 flex flex-col justify-center items-center p-0 m-auto ">
      <a href="https://www.instagram.com/nitido.barberstudio" target="_blank" rel="noopener noreferrer">
        <div class="m-auto p-0">
          <img class="max-w-full max-h-full  rounded-lg transform transition duration-300 hover:scale-105 hover:shadow-2xl" src="assets/img/logo2.png" alt="Nitido">
        </div>
      </a>
      <div class="hero-text text-center p-4 ">
        <p class="text-gray-800 text-lg md:text-xl font-light leading-relaxed">
          Tu imagen, nuestra pasión. En NITIDO, no solo te cortamos, te ayudamos a expresar tu mejor versión. ¡Ven y vive la experiencia!
        </p>
      </div>
      <div class="m-auto p-2 w-full max-w-52 bg-gray-200 bg-opacity-75 text-gray-800 rounded-lg shadow-lg transition duration-300 hover:bg-black hover:text-white">
        <a href="https://vev.co/nitido-barber-studio-es" target="_blank" rel="noopener noreferrer" class="block no-underline text-lg md:text-xl hover:font-light leading-relaxed text-center">
          <span>Reservar</span>
        </a>
      </div>
      <div class="mt-1.5 p-2 w-full max-w-52 bg-gray-200 bg-opacity-75 text-gray-800 rounded-lg shadow-lg transition duration-300 hover:bg-black hover:text-white">
        <a href="#servicios" rel="noopener noreferrer" class="no-underline block text-lg md:text-xl hover:font-light leading-relaxed text-center">
          <span>Ver los servicios</span>
        </a>
      </div>
    </div>
    <div class="col-sm-6 col-md-6 p-0 bg-cover bg-center" style="background-image: url(assets/img/image00001.jpeg)">
    </div>
  </div>
</div>
<!-- Hero End -->


<!-- Team Start -->
<div class="team py-16 bg-gray-100">
  <div class="container mx-auto">
    <div class="section-header text-center mb-12">
      <h2 class="text-6xl font-bold text-gray-800">Conozca a nuestro barbero</h2>
    </div>
    <div class="text-center p-4">
      <p class="text-gray-800 text-lg md:text-xl font-light leading-relaxed">
        En NITIDO, nos especializamos en resaltar lo mejor de tu estilo con precisión y detalle. Ya sea que busques un corte clásico, moderno o algo único, nuestro equipo está listo para ofrecerte un servicio impecable en un ambiente relajado y cómodo. Cada visita a nuestra barbería es una experiencia pensada para ti, porque sabemos que un buen corte no es solo una cuestión de apariencia, es una declaración de personalidad.      </p>
    </div>
    <div class="row flex justify-center">
      <div class="col-lg-8 col-md-8 flex justify-center">
        <div class="team-item bg-white shadow-lg rounded-lg overflow-hidden transform transition duration-300 hover:scale-105 hover:shadow-2xl">
          <a href="https://www.instagram.com/blaskkoo" class="no-underline" target="_blank" rel="noopener noreferrer">
            <div class="team-img">
              <img class="w-80 h-80 object-cover transition duration-300 transform hover:scale-110 hover:opacity-90" src="assets/img/blasko.jpeg" alt="Team Image">
            </div>
            <div class="team-text text-center p-6">
              <p class="text-2xl font-semibold text-gray-800">BLASKO</p>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Team End -->

<!-- Pricing Start -->
<div id="servicios" class="py-16 bg-gray-900 bg-cover bg-center" style="background-image: url(assets/img/image00016.jpeg)">
  <div class="container mx-auto">
    <div class="text-center mb-12">
      <h1 class="text-6xl font-bold text-white">Servicios</h1>
    </div>
    <div class="flex flex-wrap lg:flex-nowrap justify-between">
      <!-- Precios Corte -->
      <div class="w-full lg:w-2/3 mb-8 lg:mb-0 bg-gray-700 bg-opacity-60 rounded-2xl">
        <h4 class="text-3xl font-bold text-white mb-6">Precios Corte</h4>
        <ul class="grid grid-cols-1 sm:grid-cols-2 gap-6 ">
          <li class="">
            <p class="text-xl font-semibold text-white">Corte 10€</p>
            <p class="text-sm text-white">(Tiempo aprox. 40 min)</p>
          </li>
          <li>
            <p class="text-xl font-semibold text-white">Corte y Cejas 12€</p>
            <p class="text-sm text-white">(Tiempo aprox. 40 min)</p>
          </li>
          <li>
            <p class="text-xl font-semibold text-white">Corte y Barba 15€</p>
            <p class="text-sm text-white">(Tiempo aprox. 60 min)</p>
          </li>
          <li>
            <p class="text-xl font-semibold text-white">Corte y Lavado 13€</p>
            <p class="text-sm text-white">(Tiempo aprox. 45 min)</p>
          </li>
          <li>
            <p class="text-xl font-semibold text-white">Corte Niño o Jubilado 8€</p>
            <p class="text-sm text-white">(Tiempo aprox. 20 min)</p>
          </li>
          <li>
            <p class="text-xl font-semibold text-white">Corte, Barba y Cejas 17€</p>
            <p class="text-sm text-white">(Tiempo aprox. 60 min)</p>
          </li>
          <li>
            <p class="text-xl font-semibold text-white">Corte, Lavado y Barba 18€</p>
            <p class="text-sm text-white">(Tiempo aprox. 60 min)</p>
          </li>
          <li>
            <p class="text-xl font-semibold text-white">Corte, Lavado, Cejas y Barba 20€</p>
            <p class="text-sm text-white">(Tiempo aprox. 65 min)</p>
          </li>
        </ul>
      </div>
      <!-- Precios Extras -->
      <div class="w-full lg:w-1/3 bg-gray-700 bg-opacity-60 rounded-2xl">
        <h4 class="text-3xl font-bold text-white mb-6">Precios Extras</h4>
        <ul class="space-y-4">
          <li>
            <p class="text-xl font-semibold text-white">Barba 7€</p>
            <p class="text-sm text-white">(Tiempo aprox. 20 min)</p>
          </li>
          <li>
            <p class="text-xl font-semibold text-white">Cejas 2€</p>
            <p class="text-sm text-white">(Tiempo aprox. 5 min)</p>
          </li>
          <li>
            <p class="text-xl font-semibold text-white">Decoloración 60€</p>
            <p class="text-sm text-white">(Incluye corte. Tiempo aprox. 3h)</p>
          </li>
          <li>
            <p class="text-xl font-semibold text-white">Mechas 40€</p>
            <p class="text-sm text-white">(Incluye corte. Tiempo aprox. 60 min)</p>
          </li>
          <li>
            <p class="text-xl font-semibold text-white">Franjas de Colores 50€</p>
            <p class="text-sm text-white">(Incluye corte. Tiempo aprox. 2h)</p>
          </li>
          <li>
            <p class="text-xl font-semibold text-white">Permanente de Rizos 50€</p>
            <p class="text-sm text-white">(Incluye corte. Tiempo aprox. 2h)</p>
          </li>
        </ul>
      </div>
    </div>
    <div class="m-auto p-2 w-full max-w-52 bg-gray-200 bg-opacity-40 text-black font-semibold rounded-lg shadow-lg transition duration-300 hover:bg-black ">
      <a href="https://vev.co/nitido-barber-studio-es" target="_blank" rel="noopener noreferrer" class="block no-underline text-lg md:text-xl hover:font-light leading-relaxed text-center">
        <span>Reservar</span>
      </a>
    </div>
  </div>
</div>
<!-- Pricing End -->


<!-- Galeria Start -->
<div class="py-16 bg-gray-900 overflow-hidden">
  <div class="container mx-auto">
    <div class="text-center mb-12">
      <h2 class="text-5xl font-bold text-white">Galería</h2>
      <h3 class="text-lg text-white mt-4">EXPLORA NUESTRO ESPACIO</h3>
    </div>
    <div class="relative">
      <!-- Carrusel -->
      <div id="carousell" class="flex gap-6 grid-rows-2 animate-scroll">
      @for (image of images; track image.id) {
        <div class="image-item flex-none w-80 h-64 overflow-hidden rounded-lg shadow-lg">
          <img class="w-full h-full object-cover" [src]="image.url" [alt]="image.alt"/>
        </div>
      }
    </div>
    </div>
    </div>
  </div>

<!--<div id="carousel" class="flex gap-6 grid-rows-2 animate-scroll">
        Imagen 1
<div class="flex-none w-80 h-64 overflow-hidden rounded-lg shadow-lg">
  <img src="assets/img/image00008.jpeg" alt="Galería 1" class="w-full h-full object-cover">
</div>-->


<!-- Galeria End -->
